include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - unawaited_futures
    - cancel_subscriptions
    - close_sinks
    - prefer_final_locals
    - prefer_final_in_for_each
    - unnecessary_statements
    - throw_in_finally
    - avoid_dynamic_calls
